name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compilar o teste
      run: gcc test_tabuleiroox.c -o test_tabuleiroox
    - name: executar o teste
      run: ./test_tabuleiroox
    - name: compilar o programa principal
      run: gcc tabuleiroox.c -o tabuleiroox
    - name: executar o programa principal
      run: ./tabuleiroox O X X X X O O X X
